# Generated by Django 4.0.2 on 2022-07-14 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='compaign_details',
            new_name='campaign_details',
        ),
    ]
