# Generated by Django 4.0.2 on 2022-07-16 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0004_alter_chw_password_alter_organizationadmin_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Organization.location'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='recruitment_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='ward_union',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
