# Generated by Django 4.0.2 on 2022-07-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0005_supervisor_location_supervisor_recruitment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chw',
            name='recruitment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
