# Generated by Django 4.0.2 on 2022-08-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0010_quiz_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='relatedLesson',
        ),
    ]
