# Generated by Django 4.0.2 on 2022-08-14 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0011_remove_quiz_relatedlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='chw_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Organization.chw'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_id',
            field=models.IntegerField(),
        ),
    ]
