# Generated by Django 4.0.2 on 2022-08-15 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0012_notification_chw_id_alter_notification_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='chw',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Organization.chw'),
        ),
    ]
