# Generated by Django 4.0.2 on 2022-08-24 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0013_patient_chw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='visitform',
            old_name='summary_impression',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='visitform',
            name='cough_level',
        ),
        migrations.RemoveField(
            model_name='visitform',
            name='dyspnoea_level',
        ),
        migrations.RemoveField(
            model_name='visitform',
            name='headache_level',
        ),
        migrations.RemoveField(
            model_name='visitform',
            name='insomniac_level',
        ),
        migrations.RemoveField(
            model_name='visitform',
            name='nausea_level',
        ),
        migrations.RemoveField(
            model_name='visitform',
            name='other_problems',
        ),
        migrations.AlterField(
            model_name='visitform',
            name='next_visit_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='SymptomForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.symptom')),
                ('visitForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.visitform')),
            ],
        ),
    ]
