# Generated by Django 4.0.2 on 2022-08-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0014_symptom_rename_summary_impression_visitform_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitform',
            name='blood_pressure',
            field=models.CharField(max_length=10),
        ),
    ]
